### ISSUE TITLE
可以添加红点，红圈支持么？

### ISSUE THREAD

**Issue by hegelsu** [huweijian5/SegmentBarDemo#1]
![1](https://cloud.githubusercontent.com/assets/6879123/21481434/72a8431e-cba2-11e6-9596-d0924b2f8006.png)
如上图。

需求二：现有上下边距属性，需要添加左右边距属性支持，用于宽度微调

**Comment by hijunmeng** [comment]
近期会把红点加进去，至于第二个问题，由于默认是居中属性，调节左右边距可以通过调节控件的宽度来实现

**Comment by hegelsu** [comment]
红点最好有两种类型，一种就是红点，一种是数字，最好两种都要支持哦

**Comment by hijunmeng** [comment]
已支持

**Comment by hegelsu** [comment]
Nice work，非常感谢。我过几天集成一下，有问题会在这里提出。
