### ISSUE TITLE
3位数时能否美化一下？

### ISSUE THREAD

**Issue by hegelsu** [huweijian5/SegmentBarDemo#3]
3位数时能否美化一下？
![1](https://user-images.githubusercontent.com/6879123/27594477-6bc8a74e-5b8c-11e7-83ae-500ffba8db0c.png)

**Comment by hijunmeng** [comment]
一般未读数超过两位数就不用显示具体数字了

**Comment by hijunmeng** [comment]
实在要显示3位通过这个设置大一点即可setUnreadPadding

**Comment by hegelsu** [comment]
为什么显示3位数呢，是因为客户的需求，我刚开始做也是显示2位数（大于99显示99+），但客户一定要求是多少就显示多少。。。，没办法，我建议显示几位数由开发者自己来定，最多支持3位就可以了，4位就不考虑了

**Comment by hijunmeng** [comment]
的确当初没考虑3位数的情况
